baseURL = "https://kosen-meetup.netlify.com/"
DefaultContentLanguage = "ja"
title = "高専Meetup"
theme = "hyde"
hascjklanguage = true

[params]
github = "https://github.com/kosenmeetup/"
description = "高専Meetup公式サイト"
copyright = "高専Meetupネットワーク"
[[menus.main]]
name = "About"
URL = "/about/"
[[menus.main]]
name = "guideline"
URL = "/guideline/"