baseURL = "https://kosen-meetup.netlify.com/"
languageCode = "jp"
title = "高専Meetup"
theme = "herring-cove"

[params]
github = "https://github.com/kosenmeetup/"
description = "高専Meepup公式サイト"
copyright = "高専Meetupネットワーク"
[[params.links]]
name = "Home"
url = "/"
[[params.links]]
name = "About"
url = "/about/"
[[params.links]]
name = "guideline"
url = "/guideline/"