baseURL = "https://kosen-meetup.netlify.com/"
LanguageCode = "ja"
DefaultContentLanguage = "ja"
title = "高専Meetup"
theme = "hyde"
hascjklanguage = true
canonifyurls = false

[params]
github = "https://github.com/kosenmeetup/"
description = "高専Meetup公式サイト"
[[menus.main]]
name = "About"
URL = "/about/"
[[menus.main]]
name = "guideline"
URL = "/guideline/"