baseURL = "https://kosen-meetup.netlify.com/"
LanguageCode = "ja"
DefaultContentLanguage = "ja"
title = "高専Meetup"
theme = "hyde"
hascjklanguage = true
canonifyurls = false

[params]
description = "高専Meetup公式サイト"
[[menu.main]]
name = "About"
URL = "/about/"
weight = 1
[[menu.main]]
name = "Guideline"
URL = "/guideline/"
weight = 2
[[menu.main]]
name = "GitHub"
URL = "https://github.com/kosenmeetup/"
weight = 3